Implementa componente PageHeader
Sysvale/cuida pull request #408
Opened 2022-12-16 12:45 UTC by RafaelGondi

> :warning: **Estamos removendo o bootstrap como dependência de projeto**! Evite construir em cima de componentes do BootstrapVue e, se possível, evite utilizar classes do Bootstrap!

### Checklist do pull request

#### Por favor, verifique se o seu pull request está de acordo com o checklist abaixo:

-   [x] A implementação feita possui testes (Caso haja um motivo para não haver testes, descrever abaixo)
-   [x] A documentação no mdx foi feita ou atualizada, caso necessário
-   [x] O eslint passou localmente

### Tipo de pull request

-   [ ] Fix
-   [x] Feature
-   [ ] Melhoria no estilo de código (refatoração **sem** modificação na api)
-   [ ] Melhoria na escrita de métodos ou componentes (refatoração **com** modificação na api)
-   [ ] Modificação no build
-   [ ] Documentação

### Quais são os passos para avaliar o pull request?

-   1 - Teste o funcionamento do componente
-   2 - Teste o funcionamento das props
-   3 - Code Review

### Imagem ou exemplo de uso:

### Esse pull request adiciona _breaking changes_?

-   [ ] Sim
-   [x] Não

2022-12-19 14:40 UTC, patriciacoelho commented
Não sei se é o padrão mas a gente costuma quebrar a linha do subtítulo antes em alguns projetos

![image](https://user-images.githubusercontent.com/45737248/208450736-6e119bdc-b213-4ee6-b58f-46a1e65403e3.png)

2022-12-19 14:42 UTC, patriciacoelho commented
Não sei se é algo pra se pensar agora, nesse merge, mas em caso de resoluções menores fica muito desestruturado, talvez valha estudar jogar essa ações/botões para baixo

![image](https://user-images.githubusercontent.com/45737248/208451110-e8877885-e6c0-4e5f-8509-0b8d199fc4f9.png)

2022-12-19 14:46 UTC, patriciacoelho requested changes

2022-12-19 14:46 UTC, patriciacoelho commented on src/stories/components/PageHeader.stories.mdx
> +	<cds-page-header
Esse código de exemplo tá baseado em outro componente

2022-12-20 13:09 UTC, RafaelGondi commented
> Não sei se é o padrão mas a gente costuma quebrar a linha do subtítulo antes em alguns projetos
> 
> ![image](https://user-images.githubusercontent.com/45737248/208450736-6e119bdc-b213-4ee6-b58f-46a1e65403e3.png)

Tu fala com relação à proximidade do texto com os botões?

2022-12-20 14:01 UTC, patriciacoelho commented
> > Não sei se é o padrão mas a gente costuma quebrar a linha do subtítulo antes em alguns projetos
> > ![image](https://user-images.githubusercontent.com/45737248/208450736-6e119bdc-b213-4ee6-b58f-46a1e65403e3.png)
> 
> Tu fala com relação à proximidade do texto com os botões?

em relação ao container do texto geralmente ele eh só uns 50% da tela, e não tem como especificar isso nem por prop nem por slot do jeito que está atualmente o componente

2022-12-20 14:30 UTC, patriciacoelho commented
![image](https://user-images.githubusercontent.com/45737248/208690345-413eedce-d2a4-47d1-a72b-824b6f493f80.png)

acho que no modo `compact` deveria ser "space-between" entre os textos e o slot `aside`

2022-12-20 14:59 UTC, patriciacoelho approved these changes

2022-12-20 14:59 UTC, merged