Bugfix/upload input validation
Sysvale/cuida pull request #63
Opened 2020-10-27 18:11 UTC by tassiocaique

- Corrige comportamento para mostrar feedback de tipo de arquivo não aceito
- Modifica nome da propriedade 'accept' para 'allowedExtensions'

2020-10-27 18:36 UTC, patriciacoelho commented
![accept-upload-component](https://user-images.githubusercontent.com/45737248/97346193-e787c700-1869-11eb-91f8-0a237c9f2b40.gif)
Permitindo selecionar outro tipo de arquivo ao abrir janela do sistema, não sei se tem como evitar que a opção todas apareça, mas caso não dê pode botar para aparecer o feedback como no caso do drag

2020-10-27 18:38 UTC, patriciacoelho requested changes
A prop `accept` ainda está aí no storie, apesar de não parecer está sendo usada

2020-10-27 18:40 UTC, patriciacoelho requested changes
Permitindo selecionar outro tipo de arquivo ao abrir janela do sistema, não sei se tem como evitar que a opção todas apareça, mas caso não dê pode botar para aparecer o feedback como no caso do drag

2020-10-27 18:45 UTC, patriciacoelho commented
![feedback-wrong-extension](https://user-images.githubusercontent.com/45737248/97347198-31bd7800-186b-11eb-80f2-12ea914e905a.gif)
Quando seleciono o arquivo certo ele não limpa o feedback quando removo o arquivo selecionado

2020-10-27 18:52 UTC, patriciacoelho commented
acho que esse alert não ficou muito legal, talvez por causa da centralização, ou pelo fato de está dentro do componente. Não seria melhor emitir um evento de "falha" para poder dar esse feedback fora do componente?

2020-10-28 12:17 UTC, patriciacoelho commented on package.json
> +  "version": "1.3.4",
```suggestion
  "version": "1.3.6",
```
Já foi uma versão 1.3.5

2020-10-28 16:34 UTC, leolleocomp reviewed
Comentei  umas coisas na estrutura.

2020-10-28 16:34 UTC, leolleocomp commented on src/components/UploadInput.vue
>  				if (ev.dataTransfer.items[0].kind === 'file') {
```suggestion
			if (!ev.dataTransfer.items || ev.dataTransfer.items[0].kind !== 'file') return;
```

2020-10-28 16:34 UTC, leolleocomp commented on src/components/UploadInput.vue
>  			}
```suggestion
			const internalFile = ev.dataTransfer.items[0].getAsFile();
			if (this.isAValidExtension(internalFile.name)) {
				this.file = internalFile;
				this.isValid = true;
				return;
			}
			this.isValid = false;
			this.file = null;
```

2020-10-28 16:34 UTC, leolleocomp commented on src/components/UploadInput.vue
>  			}
Não consegui comentar num bloco só, mas essa sugestão depende da anterior (com os `if`s)

2020-10-28 16:34 UTC, leolleocomp commented on src/components/UploadInput.vue
> +			return true;
```suggestion
			if (this.allowedExtensions === null) return true;
			
			const alloweds = this.allowedExtensions.split(',');
			let uploaded = fileName.split('.');
			uploaded = uploaded[uploaded.length - 1].trim();
			return alloweds.filter((item) => item === uploaded).length > 0;
```

2020-10-28 17:09 UTC, tassiocaique commented on src/components/UploadInput.vue
>  				if (ev.dataTransfer.items[0].kind === 'file') {
Nesse caso, não deveria ser um `&&` ao invés de `||`?

2020-10-28 17:46 UTC, leolleocomp commented on src/components/UploadInput.vue
>  				if (ev.dataTransfer.items[0].kind === 'file') {
é não, porque inverti a comparação

2020-10-28 18:20 UTC, patriciacoelho submitted a review, later dismissed

2020-10-28 18:23 UTC, patriciacoelho commented on package.json
> +  "version": "1.3.6"
```suggestion
  "version": "1.3.6",
```

2020-10-28 18:23 UTC, patriciacoelho approved these changes

2020-10-28 18:26 UTC, merged